### ISSUE TITLE
chromium is opening but not doing anything

### ISSUE THREAD

**Issue by ohadperry** [eshaham/israeli-bank-scrapers#873]
Macbook Apple M2

what I'm seeing:
<img width="1233" alt="Screenshot at Jul 10 11-58-31" src="https://github.com/eshaham/israeli-bank-scrapers/assets/2236337/4e26a4fc-37e0-4f3d-a2a6-0dc7356f4c04">

I don't think it's related to specific scraper since I've tried leumi also 

full code 
```
 const { getPuppeteerConfig } =  require('israeli-bank-scrapers-core');

// local chromium path
//Users/ohadperry/.nvm/versions/node/v20.9.0/lib/node_modules/download-chromium/.local-chromium/chromium-mac-499413/chrome-mac/Chromium.app/Contents/MacOS/Chromium
const chromiumVersion = getPuppeteerConfig().chromiumRevision;
const { CompanyTypes, createScraper } = require('israeli-bank-scrapers-core');

(async function() {
    try {
        // read documentation below for available options
        const options = {
            companyId: CompanyTypes.leumi,
            startDate: new Date('2024-07-07'),
            combineInstallments: false,
            showBrowser: true,
            executablePath: '/Users/ohadperry/.nvm/versions/node/v20.9.0/lib/node_modules/download-chromium/.local-chromium/chromium-mac-499413/chrome-mac/Chromium.app/Contents/MacOS/Chromium'
        };

        // read documentation below for information about credentials
        const credentials = {
            username: process.env.MIZRACHI_USERNAME,
            password: process.env.MIZRACHI_PASSWORD
        };

        const scraper = createScraper(options);
        const scrapeResult = await scraper.scrape(credentials);

        if (scrapeResult.success) {
            scrapeResult.accounts.forEach((account) => {
                console.log(`found ${account.txns.length} transactions for account number ${account.accountNumber}`);
                for (const txn of account.txns) {
                    console.log(`txn is ${JSON.stringify(txn)}`);
                }
            });
        }
        else {
            throw new Error(scrapeResult.errorType);
        }
    } catch(e) {
        console.error(`scraping failed for the following reason: ${e.message}`);
    }
})();

```

**Comment by ohadperry** [comment]
plus if there is an example of github actions or aws cron as to how to run preiodically on the could without the  localhost dependency it would be great. 
I can investigate myself with a little help. 
great project btw!!

**Comment by baruchiro** [comment]
I suggest waiting for #862 to be merged because it adds a huge upgrade to Pupetteer.

**Comment by baruchiro** [comment]
Please check with the latest release

**Comment by ohadperry** [comment]
I did. it still stuck 
<img width="1199" alt="image" src="https://github.com/eshaham/israeli-bank-scrapers/assets/2236337/4a5d7a78-34dc-41e5-919c-b263fdfd2ca9">

my package.json

```
{
  "name": "bankscraper",
  "version": "1.0.0",
  "main": "index.js",
  "author": "ohad@bllink.co",
  "license": "MIT",
  "dependencies": {
    "download-chromium": "^3.0.0",
    "israeli-bank-scrapers-core": "^5.0.1"
  }
}

```

**Comment by ohadperry** [comment]
@baruchiro is there a github action yml you know works for this library? I think it will be the simplest solution

**Comment by baruchiro** [comment]
It sounds like a good idea, I don't remember if I already thought about that.

**Comment by ohadperry** [comment]
this might work

**Comment by ohadperry** [comment]
tried this and got `scraping failed for the following reason: GENERIC`


```
name: Bllink Auto detect failed bank charges
on:
  pull_request:
    branches: [ production  ]
jobs:
  markeFailedBankCharges:
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        uses: actions/setup-node@v2
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
        with:
          args: install

      - name: Install bllink dependencies
        run: yarn install --dev


      - name: Failed Bank Charges
#        uses: mujo-code/puppeteer-headful@16.6.0
#        with:
#          args: yarn run autoBankCharge
        run: yarn autoBankCharge
        env:
          CI: "true"
          MIZRACHI_USERNAME: ${{ secrets.MIZRACHI_USERNAME }}
          MIZRACHI_PASSWORD: ${{ secrets.MIZRACHI_PASSWORD }}


```
